name: Podniebienie
favicon: null
layout_spectrum: 0.258
typography_spectrum: 0.35466
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5
  lightness: 0.8667680921498686
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
