name: Podniebienie
favicon: null
layout_spectrum: 0.258
typography_spectrum: 0.35466
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Tylko najlepsze przepisy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E6DEC9'
    - '#141318'
    - '#50453F'
    - '#F6372C'
    - '#856A5F'
  brandStrength: 0.7437276
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.7204301
purpose: []
