favicon: null
name: Podniebienie
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  brandStrength: 0.7437276
  lightness: 1
  brandColors:
    - '#E6DEC9'
    - '#141318'
    - '#50453F'
    - '#F6372C'
    - '#856A5F'
  rhythmicContrast: 0.7204301
typography_spectrum: 0.35466
layout_spectrum: 0.258
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
